[theme]
primaryColor="#00f9cf"
backgroundColor="#000206"
secondaryBackgroundColor="#080250"
textColor="#0275b1"
font="monospace"


[css]
.my-square = "background-color: #00f9cf; border: 2px solid #333; padding: 10px;"


