[theme]
primaryColor="#00f9cf"
backgroundColor="#000206"
secondaryBackgroundColor="#080250"
textColor="#0275b1"
font="monospace"

[css]
.my-square {
    width: 200px;
    height: 200px;
    background-color: blue;
    border-radius: 10px; /* Define o raio dos cantos arredondados */
}
